database:
    driverClass: org.postgresql.Driver

    user: postgres

    password: postgres

    url: jdbc:postgresql://localhost:5433/passbook_example

    properties:
        charSet: UTF-8

    maxWaitForConnection: 1s

    validationQuery: "/* Health Check */ SELECT 1"

    minSize: 8

    maxSize: 32

    checkConnectionWhileIdle: false

    checkConnectionHealthWhenIdleFor: 10s

    closeConnectionIfIdleFor: 1 minute

    properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.show_sql: true

logging:
    level: INFO

    loggers:
        "com.passbook.resources.*": ALL

        org.hibernate.SQL: ALL

    console:
        enabled: true

        threshold: ALL
