database:
    driverClass: org.postgresql.Driver

    user: root

    password: root

    url: jdbc:postgresql://localhost:5432/passbook_example

    properties:
        charSet: UTF-8

    maxWaitForConnection: 1s

    validationQuery: "/* Health Check */ SELECT 1"

    minSize: 8

    maxSize: 32

    checkConnectionWhileIdle: false

    checkConnectionHealthWhenIdleFor: 10s

    closeConnectionIfIdleFor: 1 minute

#logging:
#
#    level: INFO
#
#    archivedLogFilenamePattern: ./logs/passbook-%d.logEntry.gz
#
#    archivedFileCount: 10